# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # Accept-Language.
  class AcceptLanguageEnum
    ACCEPT_LANGUAGE_ENUM = [
      # TODO: Write general description for EN
      EN = 'en'.freeze,

      # TODO: Write general description for NL
      NL = 'nl'.freeze,

      # TODO: Write general description for DE
      DE = 'de'.freeze
    ].freeze
  end
end
