# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # The product's audience group (niche/generic)
  class AudienceGroupEnum
    AUDIENCE_GROUP_ENUM = [
      # TODO: Write general description for GENERIC
      GENERIC = 'generic'.freeze,

      # TODO: Write general description for NICHE
      NICHE = 'niche'.freeze
    ].freeze
  end
end
