# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # Status of the product. One of the following
  class ChannelStatusEnum
    CHANNEL_STATUS_ENUM = [
      # TODO: Write general description for ONLINE
      ONLINE = 'online'.freeze,

      # TODO: Write general description for OFFLINE
      OFFLINE = 'offline'.freeze,

      # TODO: Write general description for ENUM_IN_PROGRESS
      ENUM_IN_PROGRESS = 'in progress'.freeze,

      # TODO: Write general description for ENUM_NOT_PROCESSED
      ENUM_NOT_PROCESSED = 'not processed'.freeze
    ].freeze
  end
end
