# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # The type of a channel
  class ChannelTypeEnum
    CHANNEL_TYPE_ENUM = [
      # TODO: Write general description for ENUM_JOB_BOARD
      ENUM_JOB_BOARD = 'job board'.freeze,

      # TODO: Write general description for ENUM_SOCIAL_MEDIA
      ENUM_SOCIAL_MEDIA = 'social media'.freeze,

      # TODO: Write general description for COMMUNITY
      COMMUNITY = 'community'.freeze,

      # TODO: Write general description for PUBLICATION
      PUBLICATION = 'publication'.freeze,

      # TODO: Write general description for AGGREGATOR
      AGGREGATOR = 'aggregator'.freeze
    ].freeze
  end
end
