# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # Content-Type.
  class ContentTypeEnum
    CONTENT_TYPE_ENUM = [
      # TODO: Write general description for ENUM_APPLICATIONJSON
      ENUM_APPLICATIONJSON = 'application/json'.freeze
    ].freeze
  end
end
