# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # ISO 4217 code for the Currency.
  class CurrencyEnum
    CURRENCY_ENUM = [
      # TODO: Write general description for EUR
      EUR = 'EUR'.freeze,

      # TODO: Write general description for USD
      USD = 'USD'.freeze,

      # TODO: Write general description for GBP
      GBP = 'GBP'.freeze
    ].freeze
  end
end
