# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # The type of employment of the posting, whether it's a permanent position or
  # a fixed time position
  class EmploymentTypeEnum
    EMPLOYMENT_TYPE_ENUM = [
      # TODO: Write general description for PERMANENT
      PERMANENT = 'permanent'.freeze,

      # TODO: Write general description for TEMPORARY
      TEMPORARY = 'temporary'.freeze,

      # TODO: Write general description for FIXED_TERM
      FIXED_TERM = 'fixed_term'.freeze,

      # TODO: Write general description for FIXED_TERM_WITH_OPTION_FOR_PERMANENT
      FIXED_TERM_WITH_OPTION_FOR_PERMANENT = 'fixed_term_with_option_for_permanent'.freeze,

      # TODO: Write general description for FREELANCE
      FREELANCE = 'freelance'.freeze,

      # TODO: Write general description for TRAINEESHIP
      TRAINEESHIP = 'traineeship'.freeze,

      # TODO: Write general description for INTERNSHIP
      INTERNSHIP = 'internship'.freeze
    ].freeze
  end
end
