# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # FacetOptionShowFacetsModel Model.
  class FacetOptionShowFacetsModel < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The facet name that becomes required when this option is chosen.
    # @return [String]
    attr_accessor :facet

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['facet'] = 'facet'
      @_hash
    end

    # An array for optional fields
    def optionals
      []
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(facet = nil,
                   additional_properties = {})
      @facet = facet unless facet == SKIP

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      facet = hash.key?('facet') ? hash['facet'] : SKIP

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      FacetOptionShowFacetsModel.new(facet,
                                     hash)
    end
  end
end
