# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # ListContractsResponseModel Model.
  class ListContractsResponseModel < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # count of elements in results
    # @return [Float]
    attr_accessor :count

    # link to get previous results
    # @return [String]
    attr_accessor :previous

    # link to get next results
    # @return [String]
    attr_accessor :mnext

    # link to get next results
    # @return [List of ContractModel]
    attr_accessor :results

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['count'] = 'count'
      @_hash['previous'] = 'previous'
      @_hash['mnext'] = 'next'
      @_hash['results'] = 'results'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        count
        previous
        mnext
        results
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(count = nil,
                   previous = nil,
                   mnext = nil,
                   results = nil,
                   additional_properties = {})
      @count = count unless count == SKIP
      @previous = previous unless previous == SKIP
      @mnext = mnext unless mnext == SKIP
      @results = results unless results == SKIP

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      count = hash.key?('count') ? hash['count'] : SKIP
      previous = hash.key?('previous') ? hash['previous'] : SKIP
      mnext = hash.key?('next') ? hash['next'] : SKIP
      # Parameter is an array, so we need to iterate through it
      results = nil
      unless hash['results'].nil?
        results = []
        hash['results'].each do |structure|
          results << (ContractModel.from_hash(structure) if structure)
        end
      end

      results = SKIP unless hash.key?('results')

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      ListContractsResponseModel.new(count,
                                     previous,
                                     mnext,
                                     results,
                                     hash)
    end
  end
end
