# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # period.
  class PeriodEnum
    PERIOD_ENUM = [
      # TODO: Write general description for YEARLY
      YEARLY = 'yearly'.freeze,

      # TODO: Write general description for MONTHLY
      MONTHLY = 'monthly'.freeze
    ].freeze
  end
end
