# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # place_type.
  class PlaceTypeEnum
    PLACE_TYPE_ENUM = [
      # TODO: Write general description for PLACE
      PLACE = 'place'.freeze,

      # TODO: Write general description for DISTRICT
      DISTRICT = 'district'.freeze,

      # TODO: Write general description for REGION
      REGION = 'region'.freeze,

      # TODO: Write general description for COUNTRY
      COUNTRY = 'country'.freeze,

      # TODO: Write general description for CONTINENT
      CONTINENT = 'continent'.freeze,

      # TODO: Write general description for WORLD
      WORLD = 'world'.freeze
    ].freeze
  end
end
