# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # PostingWorkingLocationModel Model.
  class PostingWorkingLocationModel < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :address_line1

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :address_line2

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :postcode

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :city

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :country

    # Optional parameter allowing remote work, possible values are 0 and 1,
    # defaults to 0
    # @return [Float]
    attr_accessor :allows_remote_work

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['address_line1'] = 'addressLine1'
      @_hash['address_line2'] = 'addressLine2'
      @_hash['postcode'] = 'postcode'
      @_hash['city'] = 'city'
      @_hash['country'] = 'country'
      @_hash['allows_remote_work'] = 'allowsRemoteWork'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        address_line2
        allows_remote_work
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(address_line1 = nil,
                   postcode = nil,
                   city = nil,
                   country = nil,
                   address_line2 = nil,
                   allows_remote_work = nil,
                   additional_properties = {})
      @address_line1 = address_line1 unless address_line1 == SKIP
      @address_line2 = address_line2 unless address_line2 == SKIP
      @postcode = postcode unless postcode == SKIP
      @city = city unless city == SKIP
      @country = country unless country == SKIP
      @allows_remote_work = allows_remote_work unless allows_remote_work == SKIP

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      address_line1 = hash.key?('addressLine1') ? hash['addressLine1'] : SKIP
      postcode = hash.key?('postcode') ? hash['postcode'] : SKIP
      city = hash.key?('city') ? hash['city'] : SKIP
      country = hash.key?('country') ? hash['country'] : SKIP
      address_line2 = hash.key?('addressLine2') ? hash['addressLine2'] : SKIP
      allows_remote_work =
        hash.key?('allowsRemoteWork') ? hash['allowsRemoteWork'] : SKIP

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      PostingWorkingLocationModel.new(address_line1,
                                      postcode,
                                      city,
                                      country,
                                      address_line2,
                                      allows_remote_work,
                                      hash)
    end
  end
end
