# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # PostingRequirementsModel Model.
  class PostingRequirementsModel < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :some_text

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :multiple_select_field

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :some_int_value

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['some_text'] = 'someText'
      @_hash['multiple_select_field'] = 'multipleSelectField'
      @_hash['some_int_value'] = 'someIntValue'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        some_text
        multiple_select_field
        some_int_value
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(some_text = nil,
                   multiple_select_field = nil,
                   some_int_value = nil,
                   additional_properties = {})
      @some_text = some_text unless some_text == SKIP
      @multiple_select_field = multiple_select_field unless multiple_select_field == SKIP
      @some_int_value = some_int_value unless some_int_value == SKIP

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      some_text = hash.key?('someText') ? hash['someText'] : SKIP
      multiple_select_field =
        hash.key?('multipleSelectField') ? hash['multipleSelectField'] : SKIP
      some_int_value = hash.key?('someIntValue') ? hash['someIntValue'] : SKIP

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      PostingRequirementsModel.new(some_text,
                                   multiple_select_field,
                                   some_int_value,
                                   hash)
    end
  end
end
