# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # PostingDetailsModel Model.
  class PostingDetailsModel < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The title of the posting across the different Channels where the posting
    # is going to be published.
    # @return [String]
    attr_accessor :title

    # Full description of the job posting, including all possible sections
    # **Allowed tags:** `a[href|target], em, b, br, strong, i, li, ol, p, ul`
    # @return [String]
    attr_accessor :description

    # Full description of the job posting, including all possible sections
    # **Allowed tags:** `a[href|target], em, b, br, strong, i, li, ol, p, ul`
    # @return [PostingOrganizationModel]
    attr_accessor :organization

    # Full description of the job posting, including all possible sections
    # **Allowed tags:** `a[href|target], em, b, br, strong, i, li, ol, p, ul`
    # @return [PostingWorkingLocationModel]
    attr_accessor :working_location

    # Contact is whom to contact about the job. This may be part of the posting
    # info for candidates to know whom they can reach out to learn more about
    # the vacancy.
    # @return [PostingContactInfoModel]
    attr_accessor :contact_info

    # Numbers of years of experience required for this position
    # @return [Float]
    attr_accessor :years_of_experience

    # The type of employment of the posting, whether it's a permanent position
    # or a fixed time position
    # @return [EmploymentTypeEnum]
    attr_accessor :employment_type

    # The type of employment of the posting, whether it's a permanent position
    # or a fixed time position
    # @return [PostingWeeklyWorkingHoursModel]
    attr_accessor :weekly_working_hours

    # The type of employment of the posting, whether it's a permanent position
    # or a fixed time position
    # @return [PostingSalaryIndicationModel]
    attr_accessor :salary_indication

    # Link to the page with the description of the job
    # @return [String]
    attr_accessor :job_page_url

    # Link to the page where the candidate needs to be directed when applying
    # for a position
    # @return [String]
    attr_accessor :application_url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['title'] = 'title'
      @_hash['description'] = 'description'
      @_hash['organization'] = 'organization'
      @_hash['working_location'] = 'workingLocation'
      @_hash['contact_info'] = 'contactInfo'
      @_hash['years_of_experience'] = 'yearsOfExperience'
      @_hash['employment_type'] = 'employmentType'
      @_hash['weekly_working_hours'] = 'weeklyWorkingHours'
      @_hash['salary_indication'] = 'salaryIndication'
      @_hash['job_page_url'] = 'jobPageUrl'
      @_hash['application_url'] = 'applicationUrl'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        contact_info
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(title = nil,
                   description = nil,
                   organization = nil,
                   working_location = nil,
                   years_of_experience = nil,
                   employment_type = nil,
                   weekly_working_hours = nil,
                   salary_indication = nil,
                   job_page_url = nil,
                   application_url = nil,
                   contact_info = nil,
                   additional_properties = {})
      @title = title unless title == SKIP
      @description = description unless description == SKIP
      @organization = organization unless organization == SKIP
      @working_location = working_location unless working_location == SKIP
      @contact_info = contact_info unless contact_info == SKIP
      @years_of_experience = years_of_experience unless years_of_experience == SKIP
      @employment_type = employment_type unless employment_type == SKIP
      @weekly_working_hours = weekly_working_hours unless weekly_working_hours == SKIP
      @salary_indication = salary_indication unless salary_indication == SKIP
      @job_page_url = job_page_url unless job_page_url == SKIP
      @application_url = application_url unless application_url == SKIP

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      title = hash.key?('title') ? hash['title'] : SKIP
      description = hash.key?('description') ? hash['description'] : SKIP
      organization = PostingOrganizationModel.from_hash(hash['organization']) if
        hash['organization']
      working_location = PostingWorkingLocationModel.from_hash(hash['workingLocation']) if
        hash['workingLocation']
      years_of_experience =
        hash.key?('yearsOfExperience') ? hash['yearsOfExperience'] : SKIP
      employment_type =
        hash.key?('employmentType') ? hash['employmentType'] : SKIP
      weekly_working_hours = PostingWeeklyWorkingHoursModel.from_hash(hash['weeklyWorkingHours']) if
        hash['weeklyWorkingHours']
      salary_indication = PostingSalaryIndicationModel.from_hash(hash['salaryIndication']) if
        hash['salaryIndication']
      job_page_url = hash.key?('jobPageUrl') ? hash['jobPageUrl'] : SKIP
      application_url =
        hash.key?('applicationUrl') ? hash['applicationUrl'] : SKIP
      contact_info = PostingContactInfoModel.from_hash(hash['contactInfo']) if hash['contactInfo']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      PostingDetailsModel.new(title,
                              description,
                              organization,
                              working_location,
                              years_of_experience,
                              employment_type,
                              weekly_working_hours,
                              salary_indication,
                              job_page_url,
                              application_url,
                              contact_info,
                              hash)
    end
  end
end
