# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # Contact is whom to contact about the job. This may be part of the posting
  # info for candidates to know whom they can reach out to learn more about the
  # vacancy.
  class PostingContactInfoModel < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :phone_number

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :email_address

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['phone_number'] = 'phoneNumber'
      @_hash['email_address'] = 'emailAddress'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        phone_number
        email_address
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(name = nil,
                   phone_number = nil,
                   email_address = nil,
                   additional_properties = {})
      @name = name unless name == SKIP
      @phone_number = phone_number unless phone_number == SKIP
      @email_address = email_address unless email_address == SKIP

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash.key?('name') ? hash['name'] : SKIP
      phone_number = hash.key?('phoneNumber') ? hash['phoneNumber'] : SKIP
      email_address = hash.key?('emailAddress') ? hash['emailAddress'] : SKIP

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      PostingContactInfoModel.new(name,
                                  phone_number,
                                  email_address,
                                  hash)
    end
  end
end
