# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # PostingOrganizationModel Model.
  class PostingOrganizationModel < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Name of the Company
    # @return [String]
    attr_accessor :name

    # The company Logo that wants to be used on the posting. It has to be
    # publicly available so it's picked up
    # and used for the different publishing platforms
    # @return [String]
    attr_accessor :company_logo

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['company_logo'] = 'companyLogo'
      @_hash
    end

    # An array for optional fields
    def optionals
      []
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(name = nil,
                   company_logo = nil,
                   additional_properties = {})
      @name = name unless name == SKIP
      @company_logo = company_logo unless company_logo == SKIP

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash.key?('name') ? hash['name'] : SKIP
      company_logo = hash.key?('companyLogo') ? hash['companyLogo'] : SKIP

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      PostingOrganizationModel.new(name,
                                   company_logo,
                                   hash)
    end
  end
end
