# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # ProductsDeliveryTimeModel Model.
  class ProductsDeliveryTimeModel < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :days_to_process

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :days_to_setup

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :total_days

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['days_to_process'] = 'days_to_process'
      @_hash['days_to_setup'] = 'days_to_setup'
      @_hash['total_days'] = 'total_days'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        days_to_process
        days_to_setup
        total_days
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(days_to_process = nil,
                   days_to_setup = nil,
                   total_days = nil,
                   additional_properties = {})
      @days_to_process = days_to_process unless days_to_process == SKIP
      @days_to_setup = days_to_setup unless days_to_setup == SKIP
      @total_days = total_days unless total_days == SKIP

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      days_to_process =
        hash.key?('days_to_process') ? hash['days_to_process'] : SKIP
      days_to_setup = hash.key?('days_to_setup') ? hash['days_to_setup'] : SKIP
      total_days = hash.key?('total_days') ? hash['total_days'] : SKIP

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      ProductsDeliveryTimeModel.new(days_to_process,
                                    days_to_setup,
                                    total_days,
                                    hash)
    end
  end
end
