# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # PurchasePriceModel Model.
  class PurchasePriceModel < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :currency

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :amount

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['currency'] = 'currency'
      @_hash['amount'] = 'amount'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        currency
        amount
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(currency = nil,
                   amount = nil,
                   additional_properties = {})
      @currency = currency unless currency == SKIP
      @amount = amount unless amount == SKIP

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      currency = hash.key?('currency') ? hash['currency'] : SKIP
      amount = hash.key?('amount') ? hash['amount'] : SKIP

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      PurchasePriceModel.new(currency,
                             amount,
                             hash)
    end
  end
end
