# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # The range of the time to setup required by the supplier
  class Range2Enum
    RANGE2_ENUM = [
      # TODO: Write general description for HOURS
      HOURS = 'hours'.freeze
    ].freeze
  end
end
