# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # The range of the duration
  class RangeEnum
    RANGE_ENUM = [
      # TODO: Write general description for DAYS
      DAYS = 'days'.freeze,

      # TODO: Write general description for MONTHS
      MONTHS = 'months'.freeze,

      # TODO: Write general description for YEARS
      YEARS = 'years'.freeze
    ].freeze
  end
end
