# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # The range of the time to process
  class Range1Enum
    RANGE1_ENUM = [
      # TODO: Write general description for HOURS
      HOURS = 'hours'.freeze
    ].freeze
  end
end
