# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # RequiredParameter.
  class RequiredParameterEnum
    REQUIRED_PARAMETER_ENUM = [
      # TODO: Write general description for TERM
      TERM = 'term'.freeze,

      # TODO: Write general description for CREDENTIALS
      CREDENTIALS = 'credentials'.freeze
    ].freeze
  end
end
