# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # rule.
  class RuleEnum
    RULE_ENUM = [
      # TODO: Write general description for DATE
      DATE = 'date'.freeze,

      # TODO: Write general description for EMAIL
      EMAIL = 'email'.freeze,

      # TODO: Write general description for INT
      INT = 'int'.freeze,

      # TODO: Write general description for FLOAT
      FLOAT = 'float'.freeze,

      # TODO: Write general description for REGEX
      REGEX = 'regex'.freeze,

      # TODO: Write general description for LOWER
      LOWER = 'lower'.freeze,

      # TODO: Write general description for HIGHER
      HIGHER = 'higher'.freeze,

      # TODO: Write general description for MIN
      MIN = 'min'.freeze,

      # TODO: Write general description for MAX
      MAX = 'max'.freeze,

      # TODO: Write general description for MINITEMS
      MINITEMS = 'minitems'.freeze,

      # TODO: Write general description for MAXITEMS
      MAXITEMS = 'maxitems'.freeze,

      # TODO: Write general description for MINLENGTH
      MINLENGTH = 'minlength'.freeze,

      # TODO: Write general description for MAXLENGTH
      MAXLENGTH = 'maxlength'.freeze,

      # TODO: Write general description for BEFORE
      BEFORE = 'before'.freeze,

      # TODO: Write general description for AFTER
      AFTER = 'after'.freeze,

      # TODO: Write general description for URL
      URL = 'url'.freeze,

      # TODO: Write general description for BEPC
      BEPC = 'be-pc'.freeze,

      # TODO: Write general description for BELGIUMCITY
      BELGIUMCITY = 'belgiumcity'.freeze,

      # TODO: Write general description for DECITY
      DECITY = 'de-city'.freeze,

      # TODO: Write general description for DUTCHCITY
      DUTCHCITY = 'dutchcity'.freeze,

      # TODO: Write general description for ISODATEOPTIONALTIE
      ISODATEOPTIONALTIE = 'isodateoptionaltie'.freeze,

      # TODO: Write general description for MAXLENGTHCOMBINED
      MAXLENGTHCOMBINED = 'maxlengthcombined'.freeze,

      # TODO: Write general description for MAXLEVELS
      MAXLEVELS = 'maxlevels'.freeze,

      # TODO: Write general description for NLPC
      NLPC = 'nl-pc'.freeze,

      # TODO: Write general description for NLPCSTRAAT
      NLPCSTRAAT = 'nl-pc-straat'.freeze,

      # TODO: Write general description for NOTEQUAL
      NOTEQUAL = 'notequal'.freeze,

      # TODO: Write general description for PROPERTYID
      PROPERTYID = 'propertyId'.freeze,

      # TODO: Write general description for PUSHVALUE
      PUSHVALUE = 'pushvalue'.freeze,

      # TODO: Write general description for SEPARATOR
      SEPARATOR = 'separator'.freeze,

      # TODO: Write general description for UKPC
      UKPC = 'uk-pc'.freeze,

      # TODO: Write general description for ENUM_VALIDATORCHECKKEYWORDS
      ENUM_VALIDATORCHECKKEYWORDS = 'validator:checkKeywords'.freeze,

      # TODO: Write general description for ENUM_VALIDATORINRANGE
      ENUM_VALIDATORINRANGE = 'validator:inRange'.freeze,

      # TODO: Write general description for ENUM_VALIDATORKRUISPUNT
      ENUM_VALIDATORKRUISPUNT = 'validator:kruispunt'.freeze,

      # TODO: Write general description for ENUM_VALIDATORNOTEMPTYIF
      ENUM_VALIDATORNOTEMPTYIF = 'validator:notEmptyIf'.freeze
    ].freeze
  end
end
