# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # sortBy.
  class SortByEnum
    SORT_BY_ENUM = [
      # TODO: Write general description for RELEVANT
      RELEVANT = 'relevant'.freeze,

      # TODO: Write general description for RECENT
      RECENT = 'recent'.freeze,

      # TODO: Write general description for ENUM_ORDER_FREQUENCYDESC
      ENUM_ORDER_FREQUENCYDESC = 'order_frequency.desc'.freeze,

      # TODO: Write general description for ENUM_ORDER_FREQUENCYASC
      ENUM_ORDER_FREQUENCYASC = 'order_frequency.asc'.freeze,

      # TODO: Write general description for ENUM_CREATEDDESC
      ENUM_CREATEDDESC = 'created.desc'.freeze,

      # TODO: Write general description for ENUM_CREATEDASC
      ENUM_CREATEDASC = 'created.asc'.freeze,

      # TODO: Write general description for ENUM_LIST_PRICEDESC
      ENUM_LIST_PRICEDESC = 'list_price.desc'.freeze,

      # TODO: Write general description for ENUM_LIST_PRICEASC
      ENUM_LIST_PRICEASC = 'list_price.asc'.freeze
    ].freeze
  end
end
