# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # Status of the campaign. One of the following
  class StatusEnum
    STATUS_ENUM = [
      # TODO: Write general description for ONLINE
      ONLINE = 'online'.freeze,

      # TODO: Write general description for OFFLINE
      OFFLINE = 'offline'.freeze,

      # TODO: Write general description for ENUM_IN_PROGRESS
      ENUM_IN_PROGRESS = 'in progress'.freeze
    ].freeze
  end
end
