# hapi
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Hapi
  # The type of UI and data structure to be used to input and store values for
  # this Facet.
  class TypeEnum
    TYPE_ENUM = [
      # TODO: Write general description for AUTOCOMPLETE
      AUTOCOMPLETE = 'AUTOCOMPLETE'.freeze,

      # TODO: Write general description for DATE
      DATE = 'DATE'.freeze,

      # TODO: Write general description for SELECT
      SELECT = 'SELECT'.freeze,

      # TODO: Write general description for TEXT
      TEXT = 'TEXT'.freeze,

      # TODO: Write general description for TEXTAREA
      TEXTAREA = 'TEXTAREA'.freeze,

      # TODO: Write general description for TEXTEXPAND
      TEXTEXPAND = 'TEXTEXPAND'.freeze,

      # TODO: Write general description for AREACOUNT
      AREACOUNT = 'AREACOUNT'.freeze,

      # TODO: Write general description for HIER
      HIER = 'HIER'.freeze,

      # TODO: Write general description for STATISCH
      STATISCH = 'STATISCH'.freeze,

      # TODO: Write general description for MULTIPLE
      MULTIPLE = 'MULTIPLE'.freeze,

      # TODO: Write general description for SELECTMAP_ONLY
      SELECTMAP_ONLY = 'SELECT-MAP_ONLY'.freeze
    ].freeze
  end
end
